-- Deprecated.
--
-- The AquaEdge database schema is now owned by Prisma in the backend.
-- Do not run schema creation SQL from this mock repository.
--
-- Required existing tables:
--   "Device"
--   "Telemetry"
--   "PendingCommand"
--
-- Required environment for the mock:
--   DATABASE_URL
--   DEVICE_CODE
